// RBotFirmware
// Rob Dobson 2016-2018

#include "RobotConfigurations.h"

const char *RobotConfigurations::_robotConfigs[] = {

// Sand Table Scara Matt

"{"
" \"robotType\": \"SandTableScaraAlex\","
" \"cmdsAtStart\": \"g28\","
" \"webui\":\"sand\","
" \"evaluators\":"
" {"
"   \"thrContinue\": 0"
" }"
" ,"
" \"robotGeom\":"
" {"
"   \"model\": \"SingleArmScara\","
"   \"homing\":"
"   {"
"     \"homingSeq\":\"FR1;A-10000N;#;A-10000n;#;B-10000N;#;B-10000n;#;A-24;#;B+300;#;A=h;B=h;$\","
"     \"maxHomingSecs\": 120"
"   }"
"   ,"
"   \"blockDistanceMM\": 1,"
"   \"allowOutOfBounds\": 0,"
"   \"stepEnablePin\": \"12\","
"   \"stepEnLev\": 0,"
"   \"stepDisableSecs\": 10,"
"   \"axis0\":"
"   {"
"     \"maxSpeed\": 25,"
"     \"maxAcc\": 50,"
"     \"maxRPM\": 20,"
"     \"stepsPerRot\": 9600,"
"     \"unitsPerRot\": 628.318,"
"     \"maxVal\": 190,"
"     \"stepPin\": \"14\","
"     \"dirnPin\": \"32\","
"     \"endStop0\":"
"     {"
"       \"sensePin\": \"36\","
"       \"actLvl\": 1,"
"       \"inputType\": \"INPUT_PULLUP\""
"     }"
"   }"
"   ,"
"   \"axis1\":"
"   {"
"     \"maxSpeed\": 25,"
"     \"maxAcc\": 50,"
"     \"stepsPerRot\": 9600,"
"     \"unitsPerRot\": 628.318,"
"     \"maxRPM\": 20,"
"     \"maxVal\": 190,"
"     \"stepPin\": \"33\","
"     \"dirnPin\": \"15\","
"     \"endStop0\":"
"     {"
"       \"sensePin\": \"39\","
"       \"actLvl\": 1,"
"       \"inputType\": \"INPUT_PULLUP\""
"     }"
"   }"
" }"
" ,"
" \"fileManager\":"
" {"
"   \"spiffsEnabled\": 1,"
"   \"spiffsFormatIfCorrupt\": 1,"
"   \"sdEnabled\": 1,"
"   \"sdMOSI\": \"18\","
"   \"sdMISO\": \"19\","
"   \"sdCLK\": \"5\","
"   \"sdCS\": \"21\""
" }"
" ,"
" \"wifiLed\":"
" {"
"   \"hwPin\": \"13\","
"   \"onLevel\": 1,"
"   \"onMs\": 200,"
"   \"shortOffMs\": 200,"
"   \"longOffMs\": 750"
" }"
" ,"
" \"ledStrip\":"
" {"
"   \"ledPin\": \"4\","
"   \"sensorPin\": \"34\""
" }"
"}"
    };

const int RobotConfigurations::_numRobotConfigurations = sizeof(RobotConfigurations::_robotConfigs) / sizeof(const char *);
